x-database-config-data:
  &mysql-connection-data
  environment:
    SPRING_DATASOURCE_PLATFORM: mysql
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: library


x-config-server:
  &spring-config
  environment:
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka

x-config-microsrvice:
  &spring-database-config
  environment:
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka
    - spring.datasource.url=jdbc:mysql://mysqldb:3306/library

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    image: eureka-server
    ports:
      - 8761:8761
    <<: *spring-config
    container_name: eureka-server
    networks:
      - app
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    image: api-gateway
    ports:
      - 8080:8080
    <<: *spring-config
    container_name: api-gateway
    depends_on:
      - mysqldb
      - eureka-server
      - authentication-service
      - book-service
      - library-service
    networks:
      - app
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - 0:3306
    <<: *mysql-connection-data
    container_name: mysqldb
    networks:
      - app
  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./Dockerfile
    image: authentication-service
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
      - eureka-server
    <<: *spring-database-config
    container_name: authentication-service
    networks:
      - app
  book-service:
    build:
      context: ./book-service
      dockerfile: ./Dockerfile
    image: book-service
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
      - eureka-server
      - authentication-service
    <<: *spring-database-config
    container_name: book-service
    networks:
      - app
  library-service:
    build:
      context: ./library-service
      dockerfile: ./Dockerfile
    image: library-service
    ports:
      - 8083:8083
    depends_on:
      - mysqldb
      - eureka-server
      - authentication-service
      - book-service
    <<: *spring-database-config
    container_name: library-service
    networks:
      - app
networks:
  app:

